[package]
name = "brute-tree"
version = "0.1.0"
authors = ["Alex Nichol <unixpickle@gmail.com>"]

[lib]
name = "brute_tree"
path = "src/mod.rs"

[[bin]]
name = "brute-tree-server"
path = "src/server/main.rs"

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
